[package]
name = "temporalio-protos"
version = "0.4.0"
edition = "2024"
authors = ["Temporal Technologies Inc. <sdk@temporal.io>"]
license-file = "LICENSE.txt"
description = "Compiled protobuf definitions for the Temporal Rust SDK"
homepage = "https://temporal.io/"
repository = "https://github.com/temporalio/sdk-core"
keywords = ["temporal", "protobuf"]
categories = ["development-tools"]
exclude = ["protos/*/.github/*"]
links = "temporalio_protos"

[features]
default = []
serde_serialize = []
grpc-clients = ["tonic/channel"]

[dependencies]
anyhow = "1.0"
base64 = "0.22"
derive_more = {version = "2.0", default-features = false, features = ["constructor", "display", "from", "into", "debug", "try_into"]}
http = "1"
prost = {version = "0.14"}
prost-types = {version = "0.7", package = "prost-wkt-types"}
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0"}
thiserror = {version = "2"}
tonic = {version = "0.14", default-features = false, features = ["codegen"]}
tonic-prost = {version = "0.14"}
pbjson = {version = "0.9"}

[build-dependencies]
prost = {version = "0.14"}
prost-types = "0.14"
tonic-prost-build = {version = "0.14"}
pbjson-build = {version = "0.9"}

